version: "2.0"
services:
  app:
    image: satgolden/sdforge:v3
    expose:
      - port: 9999
        as: 80
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 8
        memory:
          size: 32Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
        storage:
          - size: 30Gi
  placement:
    westcoast:
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    westcoast:
      profile: app
      count: 1
